import type { Exhibit } from '../types';

export const mockExhibits: Exhibit[] = [
  {
    id: 'starry-night',
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: '1889',
    description: 'An oil-on-canvas painting by the Dutch Post-Impressionist painter Vincent van Gogh. It depicts the view from the east-facing window of his asylum room at Saint-Rémy-de-Provence, just before sunrise, with the addition of an imaginary village.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
    relatedArtworkIds: ['the-scream', 'persistence-of-memory'],
  },
  {
    id: 'mona-lisa',
    title: 'Mona Lisa',
    artist: 'Leonardo da Vinci',
    year: 'c. 1503–1506',
    description: 'A half-length portrait painting by Italian artist Leonardo da Vinci. Considered an archetypal masterpiece of the Italian Renaissance, it has been described as "the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world".',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg',
    relatedArtworkIds: ['girl-with-a-pearl-earring', 'nefertiti-bust'],
  },
  {
    id: 'the-scream',
    title: 'The Scream',
    artist: 'Edvard Munch',
    year: '1893',
    description: 'A composition created by Norwegian artist Edvard Munch in 1893. The agonised face in the painting has become one of the most iconic images of art, seen as symbolising the anxiety of the human condition.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/800px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg',
    relatedArtworkIds: ['persistence-of-memory', 'starry-night'],
  },
  {
    id: 'girl-with-a-pearl-earring',
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: 'c. 1665',
    description: 'A famous oil painting by Dutch Golden Age painter Johannes Vermeer. It depicts a European girl wearing an exotic dress, an oriental turban, and an improbably large pearl earring.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg',
    relatedArtworkIds: ['mona-lisa', 'nefertiti-bust'],
  },
  {
    id: 'persistence-of-memory',
    title: 'The Persistence of Memory',
    artist: 'Salvador Dalí',
    year: '1931',
    description: 'A surrealist painting by Spanish artist Salvador Dalí. It is widely recognized and frequently referenced in popular culture, and is known for its striking image of soft, melting pocket watches.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/The_Persistence_of_Memory.jpg/800px-The_Persistence_of_Memory.jpg',
    relatedArtworkIds: ['the-scream'],
  },
  {
    id: 'rosetta-stone',
    title: 'Rosetta Stone',
    artist: 'Ptolemaic period',
    year: '196 BC',
    description: 'A granodiorite stele inscribed with three versions of a decree issued at Memphis, Egypt, on behalf of King Ptolemy V Epiphanes. The top and middle texts are in Ancient Egyptian using hieroglyphic and Demotic scripts respectively, while the bottom is in Ancient Greek. It was the key to deciphering Egyptian hieroglyphs.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Rosetta_Stone.JPG/800px-Rosetta_Stone.JPG',
    relatedArtworkIds: ['nefertiti-bust', 'terracotta-general', 'sutton-hoo-helmet'],
  },
  {
    id: 'nefertiti-bust',
    title: 'Bust of Nefertiti',
    artist: 'Thutmose',
    year: 'c. 1345 BC',
    description: 'A painted stucco-coated limestone bust of Nefertiti, the Great Royal Wife of Egyptian pharaoh Akhenaten. The work is believed to have been crafted in 1345 BC by the sculptor Thutmose. It is one of the most copied works of ancient Egypt.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Neues_Museum_Berlin_-_Nefertiti.jpg/800px-Neues_Museum_Berlin_-_Nefertiti.jpg',
    relatedArtworkIds: ['rosetta-stone', 'mona-lisa', 'tutankhamun-mask'],
  },
  {
    id: 'tutankhamun-mask',
    title: 'Mask of Tutankhamun',
    artist: 'Ancient Egyptian artisans',
    year: 'c. 1323 BC',
    description: 'The golden funerary mask of the 18th-dynasty ancient Egyptian Pharaoh Tutankhamun. It was discovered by Howard Carter in 1925 in tomb KV62 and is now housed in the Egyptian Museum in Cairo. The mask is one of the best-known works of art in the world.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Tuthankhamun_Golden_Mask.jpg/800px-Tuthankhamun_Golden_Mask.jpg',
    relatedArtworkIds: ['nefertiti-bust', 'rosetta-stone'],
  },
  {
    id: 'terracotta-general',
    title: 'Terracotta Army General',
    artist: 'Qin dynasty artisans',
    year: 'c. 210–209 BC',
    description: 'A figure from the Terracotta Army, a collection of terracotta sculptures depicting the armies of Qin Shi Huang, the first Emperor of China. It is a form of funerary art buried with the emperor with the purpose of protecting him in his afterlife.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Terracotta_Army_Exhibition_in_the_National_Museum_of_History_20121019-3.jpg/800px-Terracotta_Army_Exhibition_in_the_National_Museum_of_History_20121019-3.jpg',
    relatedArtworkIds: ['rosetta-stone'],
  },
  {
    id: 'sutton-hoo-helmet',
    title: 'Sutton Hoo Helmet',
    artist: 'Anglo-Saxon',
    year: 'c. 625 AD',
    description: 'An ornate Anglo-Saxon helmet discovered during the 1939 excavation of the Sutton Hoo ship-burial. It was buried around 625 and is widely believed to have been the helmet of King Rædwald of East Anglia. Its elaborate decoration may have had a protective function.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Reconstruction_of_the_Sutton_Hoo_helmet_-_British_Museum.jpg/800px-Reconstruction_of_the_Sutton_Hoo_helmet_-_British_Museum.jpg',
    relatedArtworkIds: ['rosetta-stone'],
  },
];